export const breadcumbsMapping = {
  '/': 'Inicio',
  '/offers': 'Ofertas',
  '/offers/add': 'Añadir Ofertas',
  '/offers/manage': 'Gestionar Ofertas',
  '/offers/historical': 'Histórico Ofertas',
  '/lastminute': 'Last Minute',
  '/lastminute/add': 'Añadir Last Minute',
  '/lastminute/manage': 'Gestionar Last Minute',
  '/lastminute/historical': 'Histórico Last Minute',
  '/marketsOffers': 'Comercios Proximidad',
  '/purchaseOptimizer': 'Optimizador Compra',
  '/supermarkets': 'Supermercados',
  '/marketsLastMinute': 'Last Minute',
  '/shoppingCart': 'Lista de la compra',
};
