export const productTypes = [
  { label: 'Abadejo crudo', id: 0 },
  { label: 'Abadejo', id: 1 },
  { label: 'Abadejo cocido', id: 2 },
  { label: 'Aceite de algodón', id: 3 },
  { label: 'Aceite de cacahuete', id: 4 },
  { label: 'Aceite de coco', id: 5 },
  { label: 'Aceite de colza', id: 6 },
  { label: 'Aceite de germen de trigo', id: 7 },
  { label: 'Aceite de girasol', id: 8 },
  { label: 'Aceite de hígado de bacalao', id: 9 },
  { label: 'Aceite de Maíz ', id: 10 },
  { label: 'Aceite de nuez', id: 11 },
  { label: 'Aceite de oliva', id: 12 },
  { label: 'Aceite de oliva virgen extra', id: 13 },
  { label: 'Aceite de palma', id: 14 },
  { label: 'Aceite de sésamo', id: 15 },
  { label: 'Aceite de soja', id: 16 },
  { label: 'Aceituna negra', id: 17 },
  { label: 'Aceituna verde', id: 18 },
  { label: 'Acelga cruda', id: 19 },
  { label: 'Acelga', id: 20 },
  { label: 'Acelga hervida ', id: 21 },
  { label: 'Achicoria cruda', id: 22 },
  { label: 'Achicoria cocida', id: 23 },
  { label: 'Agua con gas embotellada', id: 24 },
  { label: 'Aguacate', id: 25 },
  { label: 'Ajo', id: 26 },
  { label: 'Ajo crudo', id: 27 },
  { label: 'Albaricoque crudo', id: 28 },
  { label: 'Albóndigas', id: 29 },
  { label: 'Alcachofa cruda', id: 30 },
  { label: 'Alcachofa', id: 31 },
  { label: 'Alcachofa hervida', id: 32 },
  { label: 'Alcaparra ', id: 33 },
  { label: 'Alfalfa', id: 34 },
  { label: 'Alga nori', id: 35 },
  { label: 'Alga wakame ', id: 36 },
  { label: 'Alioli ', id: 37 },
  { label: 'Almeja cruda', id: 38 },
  { label: 'Almeja congelada', id: 39 },
  { label: 'Almeja hervida ', id: 40 },
  { label: 'Almeja', id: 41 },
  { label: 'Almendra cruda', id: 42 },
  { label: 'Almendra tostada ', id: 43 },
  { label: 'Almendra frita salada', id: 44 },
  { label: 'Almidón de arroz ', id: 45 },
  { label: 'Almidón de maíz', id: 46 },
  { label: 'Almidón de trigo', id: 47 },
  { label: 'Altramuces', id: 48 },
  { label: 'Altramuces cocidos', id: 49 },
  { label: 'Alubia blanca hervida', id: 50 },
  { label: 'Alubia blanca cruda', id: 51 },
  { label: 'Alubia blanca', id: 52 },
  { label: 'Alubia negra seca remojada hervida', id: 53 },
  { label: 'Anacardo crudo', id: 54 },
  { label: 'Anchoa', id: 55 },
  { label: 'Anchoas crudas', id: 56 },
  { label: 'Anchoas', id: 57 },
  { label: 'Anguila', id: 58 },
  { label: 'Anguila cruda', id: 59 },
  { label: 'Anguila hervida', id: 60 },
  { label: 'Angula cruda', id: 61 },
  { label: 'Angula', id: 62 },
  { label: 'Angulas cocidas', id: 63 },
  { label: 'Anís seco', id: 64 },
  { label: 'Apio crudo', id: 65 },
  { label: 'Apio', id: 66 },
  { label: 'Apio hervido ', id: 67 },
  { label: 'Arándanos', id: 68 },
  { label: 'Arenque crudo', id: 69 },
  { label: 'Arenque cocido', id: 70 },
  { label: 'Arenque ahumado', id: 71 },
  { label: 'Arenque salado', id: 72 },
  { label: 'Arroz blanco crudo', id: 73 },
  { label: 'Arroz blanco hervido', id: 74 },
  { label: 'Arroz integral crudo', id: 75 },
  { label: 'Arroz integral hervido', id: 76 },
  { label: 'Arroz blanco precocido o cocción rápida crudo', id: 77 },
  { label: 'Arroz con leche', id: 78 },
  { label: 'Arroz hinchado', id: 79 },
  { label: 'Aspartamo', id: 80 },
  { label: 'Atún', id: 81 },
  { label: 'Atún crudo', id: 82 },
  { label: 'Atún enlatado', id: 83 },
  { label: 'Avellana cruda', id: 84 },
  { label: 'Avellana tostada', id: 85 },
  { label: 'Avena', id: 86 },
  { label: 'Avena cruda', id: 87 },
  { label: 'Avena cocida', id: 88 },
  { label: 'Azafrán', id: 89 },
  { label: 'Azúcar', id: 90 },
  { label: 'Azúcar glas', id: 91 },
  { label: 'Azucar moreno', id: 92 },
  { label: 'Bacaladilla cruda', id: 93 },
  { label: 'Bacaladilla congelada', id: 94 },
  { label: 'Bacaladilla', id: 95 },
  { label: 'Bacalao fresco', id: 96 },
  { label: 'Bacalao salado remojado hervido', id: 97 },
  { label: 'Bacalao fresco crudo', id: 98 },
  { label: 'Bacalao frito', id: 99 },
  { label: 'Bacalao ahumado', id: 100 },
  { label: 'Bacalao', id: 101 },
  { label: 'Bacalao salado crudo', id: 102 },
  { label: 'Bacalao salado remojado crudo', id: 103 },
  { label: 'Bacon ahumado', id: 104 },
  { label: 'Barra chocolate tipo bounty', id: 105 },
  { label: 'Barra de chocolate tipo Mars', id: 106 },
  { label: 'Barra de chocolate tipo Kit-Kat', id: 107 },
  { label: 'Barrita de chocolate tipo s/e', id: 108 },
  { label: 'Barrita cereales con fruta', id: 109 },
  { label: 'Barrita cereales Maíz y trigo', id: 110 },
  { label: 'Barrita de cereales  trigo y chocolate', id: 111 },
  { label: 'Batido de chocolate', id: 112 },
  { label: 'Batido lácteo sabor s/e', id: 113 },
  { label: 'Batido de fresa', id: 114 },
  { label: 'Batido de soja ', id: 115 },
  { label: 'Bebida isotónica', id: 116 },
  { label: 'Bebida vegetal de almendras ', id: 117 },
  { label: 'Bebida vegetal de arroz', id: 118 },
  { label: 'Bebida vegetal de avena ', id: 119 },
  { label: 'Bebida vegetal de coco ', id: 120 },
  { label: 'Bebida vegetal de espelta', id: 121 },
  { label: 'Bebida vegetal de soja', id: 122 },
  { label: 'Berberecho crudo', id: 123 },
  { label: 'Berberecho cocido', id: 124 },
  { label: 'Berberecho', id: 125 },
  { label: 'Berberecho enlatado', id: 126 },
  { label: 'Berenjena cruda', id: 127 },
  { label: 'Berenjena', id: 128 },
  { label: 'Berenjena frita', id: 129 },
  { label: 'Berenjena hervida', id: 130 },
  { label: 'Berro crudo', id: 131 },
  { label: 'Berro cocido', id: 132 },
  { label: 'Bicarbonato', id: 133 },
  { label: 'Bígaro hervido', id: 134 },
  { label: 'Bígaro', id: 135 },
  { label: 'Bígaro asado', id: 136 },
  { label: 'Biscote', id: 137 },
  { label: 'Bizcocho ', id: 138 },
  { label: 'Bogavante crudo', id: 139 },
  { label: 'Bogavante', id: 140 },
  { label: 'Bogavante hervido', id: 141 },
  { label: 'Bollo de leche ', id: 142 },
  { label: 'Bollo relleno de chocolate', id: 143 },
  { label: 'Boniato crudo', id: 144 },
  { label: 'Boniato asado', id: 145 },
  { label: 'Boniato hervido', id: 146 },
  { label: 'Boniato', id: 147 },
  { label: 'Bonito del Norte', id: 148 },
  { label: 'Bonito del Norte crudo', id: 149 },
  { label: 'Bonito del Norte enlatado', id: 150 },
  { label: 'Boqueron crudo', id: 151 },
  { label: 'Boqueron', id: 152 },
  { label: 'Boquerón frito', id: 153 },
  { label: 'Breca cruda', id: 154 },
  { label: 'Breca', id: 155 },
  { label: 'Brócoli crudo', id: 156 },
  { label: 'Brócoli hervido', id: 157 },
  { label: 'Brócoli', id: 158 },
  { label: 'Butifarra blanca', id: 159 },
  { label: 'Butifarra blanca cocida', id: 160 },
  { label: 'Caballa', id: 161 },
  { label: 'Caballa cruda', id: 162 },
  { label: 'Caballa congelada', id: 163 },
  { label: 'Caballa enlatada', id: 164 },
  { label: 'Caballo parte s/e crudo', id: 165 },
  { label: 'Caballo cocido', id: 166 },
  { label: 'Caballo', id: 167 },
  { label: 'Cabracho o rascacio crudo', id: 168 },
  { label: 'Cabracho o rascacio', id: 169 },
  { label: 'Cacahuete crudo', id: 170 },
  { label: 'Cacahuete crudo con cáscara', id: 171 },
  { label: 'Cacahuete frito salado', id: 172 },
  { label: 'Cacahuete tostado salado', id: 173 },
  { label: 'Cacahuete tostado sin sal', id: 174 },
  { label: 'Cacao soluble', id: 175 },
  { label: 'Cacao puro', id: 176 },
  { label: 'Café con leche', id: 177 },
  { label: 'Café con leche desnatada con Azúcar', id: 178 },
  { label: 'Café', id: 179 },
  { label: 'Café molido', id: 180 },
  { label: 'Café sucedáneo soluble', id: 181 },
  { label: 'Calabacín asado', id: 182 },
  { label: 'Calabacín', id: 183 },
  { label: 'Calabacín crudo', id: 184 },
  { label: 'Calabacín hervido', id: 185 },
  { label: 'Calabaza cruda ', id: 186 },
  { label: 'Calabaza hervida', id: 187 },
  { label: 'Calabaza', id: 188 },
  { label: 'Calabaza asada', id: 189 },
  { label: 'Calamar asado', id: 190 },
  { label: 'Calamar', id: 191 },
  { label: 'Calamar crudo', id: 192 },
  { label: 'Calamar conserva', id: 193 },
  { label: 'Calamar frito', id: 194 },
  { label: 'Caldo de Pollo', id: 195 },
  { label: 'Caldo vegetal ', id: 196 },
  { label: 'Callos de ternera crudo', id: 197 },
  { label: 'Callos de ternera cocidos', id: 198 },
  { label: 'Canela', id: 199 },
  { label: 'Canelones de carne s/e con bechamel', id: 200 },
  { label: 'Cangrejo buey', id: 201 },
  { label: 'Cangrejo de río crudo', id: 202 },
  { label: 'Cangrejo', id: 203 },
  { label: 'Canónigos crudo', id: 204 },
  { label: 'Caqui con piel crudo', id: 205 },
  { label: 'Cardo', id: 206 },
  { label: 'Cardo tallo crudo', id: 207 },
  { label: 'Cardo cocido', id: 208 },
  { label: 'Carne picada sazonada para relle0 cruda', id: 209 },
  { label: 'Carpa', id: 210 },
  { label: 'Carpa cruda', id: 211 },
  { label: 'Castaña cruda', id: 212 },
  { label: 'Castaña tostada', id: 213 },
  { label: 'Cava o champán', id: 214 },
  { label: 'Caviar', id: 215 },
  { label: 'Cebada cruda', id: 216 },
  { label: 'Cebada cocida', id: 217 },
  { label: 'Cebolla asada', id: 218 },
  { label: 'Cebolla blanca cruda', id: 219 },
  { label: 'Cebolla blanca hervida', id: 220 },
  { label: 'Cebolla morada', id: 221 },
  { label: 'Cebollino crudo', id: 222 },
  { label: 'Centeno crudo', id: 223 },
  { label: 'Centeno cocido', id: 224 },
  { label: 'Centollo crudo', id: 225 },
  { label: 'Centollo', id: 226 },
  { label: 'Centollo cocido', id: 227 },
  { label: 'Cerdo chuleta', id: 228 },
  { label: 'Cerdo chuleta con grasa vi1ble cruda', id: 229 },
  { label: 'Cerdo costilla cruda', id: 230 },
  { label: 'Cerdo costilla', id: 231 },
  { label: 'Cerdo costilla cocida', id: 232 },
  { label: 'Cerdo lomo asado', id: 233 },
  { label: 'Cerdo lomo', id: 234 },
  { label: 'Cerdo lomo crudo', id: 235 },
  { label: 'Cerdo panceta', id: 236 },
  { label: 'Cerdo panceta cruda', id: 237 },
  { label: 'Cerdo solomillo asado', id: 238 },
  { label: 'Cerdo solomillo', id: 239 },
  { label: 'Cerdo solomillo crudo', id: 240 },
  { label: 'Cerdo tocino crudo', id: 241 },
  { label: 'Cereales base trigo y chocolate', id: 242 },
  { label: 'Cereales desayuno base de arroz chocolateado', id: 243 },
  { label: 'Cereales desayuno base de arroz y miel', id: 244 },
  { label: 'Cereales desayuno base de arroz trigo y fruta', id: 245 },
  { label: 'Cereales desayuno base de Maíz y miel', id: 246 },
  { label: 'Cereales desayuno base de Maíz y trigo', id: 247 },
  { label: 'Cereales desayuno base de Maíz trigo y avena', id: 248 },
  { label: 'Cereales desayuno base de trigo azucarado', id: 249 },
  { label: 'Cereales desayuno base de trigo y arroz', id: 250 },
  { label: 'Cereales desayuno base de trigo y frutas', id: 251 },
  { label: 'Cereales desayuno base de trigo y miel', id: 252 },
  { label: 'Cereales desayuno base de trigo avena Maíz y miel', id: 253 },
  { label: 'Cereales desayuno base de trigo avena Maíz miel y nueces', id: 254 },
  { label: 'Cereales desayuno base muesli ', id: 255 },
  { label: 'Cereales desayuno Maíz azucarado', id: 256 },
  { label: 'Cereales', id: 257 },
  { label: 'Cereales rellenos de chocolate', id: 258 },
  { label: 'Cereales tipo chocoflakes (Chocapic)', id: 259 },
  { label: 'Cereza cruda', id: 260 },
  { label: 'Cerveza oscura 8°- 9°', id: 261 },
  { label: 'Cerveza rubia 4°-5°', id: 262 },
  { label: 'Cerveza con alcohol', id: 263 },
  { label: 'Champiñón crudo', id: 264 },
  { label: 'Champiñón', id: 265 },
  { label: 'Champiñón cocido', id: 266 },
  { label: 'Chile rojo', id: 267 },
  { label: 'Chile verde', id: 268 },
  { label: 'Chiriví\xada cruda', id: 269 },
  { label: 'Chiriví\xada cocida', id: 270 },
  { label: 'Chocolate >70%', id: 271 },
  { label: 'Chocolate >85% ', id: 272 },
  { label: 'Chocolate 90%', id: 273 },
  { label: 'Chocolate negro', id: 274 },
  { label: 'Chocolate', id: 275 },
  { label: 'Chocolate blanco', id: 276 },
  { label: 'Chocolate con leche', id: 277 },
  { label: 'Chocolate con leche y almendras', id: 278 },
  { label: 'Chocolate con leche y arroz', id: 279 },
  { label: 'Chocolate con nueces de macadamia', id: 280 },
  { label: 'Chocolate negro con almendras', id: 281 },
  { label: 'Chocolate negro con Azúcar', id: 282 },
  { label: 'Chorizo categorí\xada s/e', id: 283 },
  { label: 'Chufa cruda', id: 284 },
  { label: 'Churros', id: 285 },
  { label: 'Ciervo parte s/e crudo con grasa separable', id: 286 },
  { label: 'Ciruela con piel cruda', id: 287 },
  { label: 'Ciruela seca', id: 288 },
  { label: 'Ciruela con piel', id: 289 },
  { label: 'Coco seco', id: 290 },
  { label: 'Coco fresco crudo', id: 291 },
  { label: 'Col blanca hervida', id: 292 },
  { label: 'Col blanca cruda', id: 293 },
  { label: 'Col de Bruselas cruda', id: 294 },
  { label: 'Col de Bruselas hervida', id: 295 },
  { label: 'Col de bruselas', id: 296 },
  { label: 'Col lombarda cruda', id: 297 },
  { label: 'Col lombarda hervida', id: 298 },
  { label: 'Col lombarda', id: 299 },
  { label: 'Col repollo cruda', id: 300 },
  { label: 'Col repollo hervida', id: 301 },
  { label: 'Col rizada cruda', id: 302 },
  { label: 'Coliflor congelada cruda', id: 303 },
  { label: 'Coliflor cruda', id: 304 },
  { label: 'Coliflor hervida', id: 305 },
  { label: 'Coliflor', id: 306 },
  { label: 'Comino', id: 307 },
  { label: 'Conejo de granja carne cruda', id: 308 },
  { label: 'Conejo entero crudo', id: 309 },
  { label: 'Conejo entero estofado', id: 310 },
  { label: 'Conejo entero asado', id: 311 },
  { label: 'Confitura fruta s/e', id: 312 },
  { label: 'Confitura frutas s/e baja', id: 313 },
  { label: 'Coñac', id: 314 },
  { label: 'Corazón de cordero crudo', id: 315 },
  { label: 'Corazón de pollo crudo', id: 316 },
  { label: 'Corazón de cerdo crudo', id: 317 },
  { label: 'Corazón de vaca/buey cocido', id: 318 },
  { label: 'Corazón de vaca/buey crudo', id: 319 },
  { label: 'Cordero costilla/chuleta con grasa', id: 320 },
  { label: 'Cordero costilla/chuleta con grasa cruda', id: 321 },
  { label: 'Cordero paletilla con grasa asada', id: 322 },
  { label: 'Corderon paletilla con grasa cruda', id: 323 },
  { label: 'Cordero paletilla con grasa asada ', id: 324 },
  { label: 'Cordero paletilla con grasa cruda', id: 325 },
  { label: 'Cordero pierna con grasa asada', id: 326 },
  { label: 'Cordero pierna con grasa cruda', id: 327 },
  { label: 'Crema catalana', id: 328 },
  { label: 'Crema de almendras envasada con reconstituir', id: 329 },
  { label: 'Crema de cacahuete', id: 330 },
  { label: 'Crema de cacahuete 100% con Azúcar', id: 331 },
  { label: 'Crema de chocolate con avellanas', id: 332 },
  { label: 'Crema de chocolate y nata', id: 333 },
  { label: 'Crema de chocolate baja', id: 334 },
  { label: 'Crema de coco', id: 335 },
  { label: 'Crema de vainilla y mousse de chocolate', id: 336 },
  { label: 'Crema inglesa', id: 337 },
  { label: 'Crema pastelera', id: 338 },
  { label: 'Croissant', id: 339 },
  { label: 'Croissant de chocolate', id: 340 },
  { label: 'Croqueta de pescado frita con aceite s/e', id: 341 },
  { label: 'Croqueta de Jamón ', id: 342 },
  { label: 'Croqueta de Pollo cruda', id: 343 },
  { label: 'Cuajada', id: 344 },
  { label: 'Curry', id: 345 },
  { label: 'Dátil seco', id: 346 },
  { label: 'Donut comercial', id: 347 },
  { label: 'Donut de chocolate', id: 348 },
  { label: 'Dorada cruda', id: 349 },
  { label: 'Dorada congelada', id: 350 },
  { label: 'Dorada plancha', id: 351 },
  { label: 'Dorada', id: 352 },
  { label: 'Edamame', id: 353 },
  { label: 'Empanadilla de Atún frita', id: 354 },
  { label: 'Empanadillas de carne fritas con aceite s/e', id: 355 },
  { label: 'Empanadillas de queso fritas con aceite s/e', id: 356 },
  { label: 'Endibia cruda', id: 357 },
  { label: 'Endibia cocida', id: 358 },
  { label: 'Eneldo seco', id: 359 },
  { label: 'Ensaimada ', id: 360 },
  { label: 'Ensaladilla rusa', id: 361 },
  { label: 'Escarola cruda', id: 362 },
  { label: 'Espárrago blanco', id: 363 },
  { label: 'Espárrago verde hervido', id: 364 },
  { label: 'Espárrago verde', id: 365 },
  { label: 'Espárrago pelado crudo', id: 366 },
  { label: 'Espinaca cruda', id: 367 },
  { label: 'Espinaca', id: 368 },
  { label: 'Espinaca hervida', id: 369 },
  { label: 'Espinaca picada congelada cruda', id: 370 },
  { label: 'Fécula de Maíz', id: 371 },
  { label: 'Flan de huevo', id: 372 },
  { label: 'Flan de huevo bajo', id: 373 },
  { label: 'Flan de vainilla', id: 374 },
  { label: 'Foie de pato', id: 375 },
  { label: 'Frambuesa cruda', id: 376 },
  { label: 'Fresa', id: 377 },
  { label: 'Fresón crudo', id: 378 },
  { label: 'Fritos de Maíz', id: 379 },
  { label: 'Fructosa', id: 380 },
  { label: 'Fuet', id: 381 },
  { label: 'Galleta  tipo digestiva con chocolate', id: 382 },
  { label: 'Galleta salada', id: 383 },
  { label: 'Galletas con chocolate tipo cookies', id: 384 },
  { label: 'Galleta crujiente tipo cracker', id: 385 },
  { label: 'Galleta barquillo con jalea de frutas', id: 386 },
  { label: 'Galleta doble tipo Principe con chocolate', id: 387 },
  { label: 'Galleta tipo Digestiva', id: 388 },
  { label: 'Galleta tipo María', id: 389 },
  { label: 'Galletas de mantequilla', id: 390 },
  { label: 'Galleta integral', id: 391 },
  { label: 'Galleta cubierta de chocolate', id: 392 },
  { label: 'Galletas saladas con queso', id: 393 },
  { label: 'Gallina con piel hervida', id: 394 },
  { label: 'Gallina entera cruda', id: 395 },
  { label: 'Gallo crudo', id: 396 },
  { label: 'Gamba quisquilla congelada', id: 397 },
  { label: 'Gamba quisquilla cruda', id: 398 },
  { label: 'Gamba quisquilla', id: 399 },
  { label: 'Gamba quisquilla hervida', id: 400 },
  { label: 'Gamba roja cruda', id: 401 },
  { label: 'Gamba hervida', id: 402 },
  { label: 'Gamba roja', id: 403 },
  { label: 'Garbanzo seco remojado hervido ', id: 404 },
  { label: 'Garbanzo', id: 405 },
  { label: 'Garbanzo tostado', id: 406 },
  { label: 'Garbanzo seco crudo', id: 407 },
  { label: 'Gazpacho', id: 408 },
  { label: 'Gelatina', id: 409 },
  { label: 'Germen de trigo', id: 410 },
  { label: 'Gominola genérica', id: 411 },
  { label: 'Granada cruda', id: 412 },
  { label: 'Grosella negra cruda', id: 413 },
  { label: 'Grosella cruda', id: 414 },
  { label: 'Guayaba enlatada', id: 415 },
  { label: 'Guayaba con piel cruda', id: 416 },
  { label: 'Guindilla', id: 417 },
  { label: 'Guindilla picante', id: 418 },
  { label: 'Guisante', id: 419 },
  { label: 'Guisante seco crudo', id: 420 },
  { label: 'Guisante fresco crudo', id: 421 },
  { label: 'Guisante fresco hervido', id: 422 },
  { label: 'Gusanitos de Maíz', id: 423 },
  { label: 'Haba seca', id: 424 },
  { label: 'Haba seca remojada hervida', id: 425 },
  { label: 'Haba fresca', id: 426 },
  { label: 'Haba frita', id: 427 },
  { label: 'Harina de arroz', id: 428 },
  { label: 'Harina de avena cocida', id: 429 },
  { label: 'Harina de avena', id: 430 },
  { label: 'Harina de cebada', id: 431 },
  { label: 'Harina de centeno', id: 432 },
  { label: 'Harina de espelta integral', id: 433 },
  { label: 'Harina de trigo', id: 434 },
  { label: 'Harina de trigo integral', id: 435 },
  { label: 'Harina de Maíz', id: 436 },
  { label: 'Harina de soja', id: 437 },
  { label: 'Helado cremoso tipo s/e', id: 438 },
  { label: 'Helado cremoso vainilla', id: 439 },
  { label: 'Helado de chocolate', id: 440 },
  { label: 'Helado de fresa', id: 441 },
  { label: 'Helado de nata ', id: 442 },
  { label: 'Hí\xadgado cordero crudo', id: 443 },
  { label: 'Hí\xadgado de pollo crudo', id: 444 },
  { label: 'Hí\xadgado de ternera crudo', id: 445 },
  { label: 'Hí\xadgado de cerdo crudo', id: 446 },
  { label: 'Hí\xadgado de vaca/buey crudo', id: 447 },
  { label: 'Higo crudo', id: 448 },
  { label: 'Brevas', id: 449 },
  { label: 'Hinojo crudo', id: 450 },
  { label: 'Hojaldre', id: 451 },
  { label: 'Horchata', id: 452 },
  { label: 'Huevo de gallina clara cruda', id: 453 },
  { label: 'Huevo de gallina entero crudo', id: 454 },
  { label: 'Huevo de gallina escalfado', id: 455 },
  { label: 'Huevo de gallina frito', id: 456 },
  { label: 'Huevo de gallina hervido duro', id: 457 },
  { label: 'Huevo de gallina pasado por agua', id: 458 },
  { label: 'Huevo de gallina revuelto con mantequilla', id: 459 },
  { label: 'Huevo de gallina yema cruda', id: 460 },
  { label: 'Huevo de pato crudo', id: 461 },
  { label: 'Huevo de codorniz entero crudo', id: 462 },
  { label: 'Huevo de pavo entero crudo', id: 463 },
  { label: 'Infusión ', id: 464 },
  { label: 'Jalea real', id: 465 },
  { label: 'Jamón cocido extra', id: 466 },
  { label: 'Jamón asado', id: 467 },
  { label: 'Jamón curado con grasa ', id: 468 },
  { label: 'Jamón curado sin grasa', id: 469 },
  { label: 'Jengibre', id: 470 },
  { label: 'Judí\xada verde cruda', id: 471 },
  { label: 'Judí\xada verde hervida', id: 472 },
  { label: 'Judí\xada verde', id: 473 },
  { label: 'Judí\xada verde congelada cruda', id: 474 },
  { label: 'Judí\xada blanca', id: 475 },
  { label: 'Judí\xadas blancas cocidas', id: 476 },
  { label: 'Judí\xada pinta', id: 477 },
  { label: 'Judí\xada pinta cocida', id: 478 },
  { label: 'Jurel crudo', id: 479 },
  { label: 'Jurel cocido', id: 480 },
  { label: 'Jurel', id: 481 },
  { label: 'Kéfir', id: 482 },
  { label: 'Ketchup', id: 483 },
  { label: 'Kiwi crudo', id: 484 },
  { label: 'Lacón', id: 485 },
  { label: 'Langosta cruda', id: 486 },
  { label: 'Langosta cocida', id: 487 },
  { label: 'Langosta', id: 488 },
  { label: 'Langostino crudo', id: 489 },
  { label: 'Langostino cocido', id: 490 },
  { label: 'Langostino', id: 491 },
  { label: 'Lasaña s/e bechamel', id: 492 },
  { label: 'Laurel hoja', id: 493 },
  { label: 'Leche con omega 3 desnatada', id: 494 },
  { label: 'Leche condensada entera con Azúcar', id: 495 },
  { label: 'Leche de cabra', id: 496 },
  { label: 'Leche de almendra', id: 497 },
  { label: 'Leche de oveja', id: 498 },
  { label: 'Leche evaporada entera', id: 499 },
  { label: 'Leche entera UHT', id: 500 },
  { label: 'Leche semidesnatada UHT', id: 501 },
  { label: 'Leche desnatada UHT', id: 502 },
  { label: 'Leche entera pasteurizada', id: 503 },
  { label: 'Leche semidesnatada pasteurizada', id: 504 },
  { label: 'Leche desnatada pasteurizada', id: 505 },
  { label: 'Leche', id: 506 },
  { label: 'Leche merengada', id: 507 },
  { label: 'Leche sin lactosa desnatada', id: 508 },
  { label: 'Leche sin lactosa entera', id: 509 },
  { label: 'Leche sin lactosa semidesnatada', id: 510 },
  { label: 'Leche fermentada Bifidobacterium desnatada natural', id: 511 },
  { label: 'Leche fermentada Bifidobacterium entera con frutas', id: 512 },
  { label: 'Leche fermentada Bifidobacterium entera natural', id: 513 },
  { label: 'Lechuga', id: 514 },
  { label: 'Lecitina de soja', id: 515 },
  { label: 'Lengua de cerdo cruda', id: 516 },
  { label: 'Lengua de cordero cruda', id: 517 },
  { label: 'Lengua de buey cruda', id: 518 },
  { label: 'Lengua de ternera cruda', id: 519 },
  { label: 'Lenguado', id: 520 },
  { label: 'Lenguado frito', id: 521 },
  { label: 'Lenguado crudo', id: 522 },
  { label: 'Lenteja', id: 523 },
  { label: 'Lenteja seca cruda', id: 524 },
  { label: 'Lenteja seca remojada hervida', id: 525 },
  { label: 'Levadura fresca', id: 526 },
  { label: 'Liebre guisada', id: 527 },
  { label: 'Liebre entera cruda', id: 528 },
  { label: 'Lija cruda', id: 529 },
  { label: 'Lija', id: 530 },
  { label: 'Lima cruda', id: 531 },
  { label: 'Limón crudo', id: 532 },
  { label: 'Limón zumo fresco', id: 533 },
  { label: 'Litchi crudo', id: 534 },
  { label: 'Lomo embuchado', id: 535 },
  { label: 'Longaniza', id: 536 },
  { label: 'Longaniza de magro', id: 537 },
  { label: 'Longaniza de pavo', id: 538 },
  { label: 'Lubina cruda', id: 539 },
  { label: 'Lubina', id: 540 },
  { label: 'Lubina congelada', id: 541 },
  { label: 'Lucio crudo', id: 542 },
  { label: 'Lucio', id: 543 },
  { label: 'Macedonia de frutas conserva', id: 544 },
  { label: 'Macedonia de frutas enlatada', id: 545 },
  { label: 'Magdalena ', id: 546 },
  { label: 'Maíz dulce', id: 547 },
  { label: 'Maíz', id: 548 },
  { label: 'Maizena', id: 549 },
  { label: 'Maltitol', id: 550 },
  { label: 'Mandarina', id: 551 },
  { label: 'Mango crudo', id: 552 },
  { label: 'Manteca de cerdo', id: 553 },
  { label: 'Mantequilla baja', id: 554 },
  { label: 'Mantequilla', id: 555 },
  { label: 'Mantequilla salada', id: 556 },
  { label: 'Manzana compota con Azúcar', id: 557 },
  { label: 'Manzana con piel', id: 558 },
  { label: 'Manzana con piel cruda', id: 559 },
  { label: 'Manzana variedad s/e cruda', id: 560 },
  { label: 'Manzana Golden con piel cruda', id: 561 },
  { label: 'Manzana Starking con piel cruda', id: 562 },
  { label: 'Maracuyá', id: 563 },
  { label: 'Margarina', id: 564 },
  { label: 'Margarina light', id: 565 },
  { label: 'Margarina 3/4 vegetal', id: 566 },
  { label: 'Margarina vegetal enriquecida', id: 567 },
  { label: 'Masa brisa horneada', id: 568 },
  { label: 'Masa de hojaldre', id: 569 },
  { label: 'Masa de hojaldre horneada', id: 570 },
  { label: 'Masa de pizza', id: 571 },
  { label: 'Mayonesa aceite s/e comercial', id: 572 },
  { label: 'Mayonesa light comercial', id: 573 },
  { label: 'Mayonesa aceite de oliva', id: 574 },
  { label: 'Mayonesa aceite de girasol', id: 575 },
  { label: 'Mayonesa aceite de soja', id: 576 },
  { label: 'Mazapán', id: 577 },
  { label: 'Mejillón crudo', id: 578 },
  { label: 'Mejillón', id: 579 },
  { label: 'Mejillón hervido', id: 580 },
  { label: 'Melocotón con piel crudo', id: 581 },
  { label: 'Melocotón desecado', id: 582 },
  { label: 'Melocotón', id: 583 },
  { label: 'Melón crudo', id: 584 },
  { label: 'Melón tipo Canteloupe crudo', id: 585 },
  { label: 'Melindre', id: 586 },
  { label: 'Membrillo crudo', id: 587 },
  { label: 'Menestra de verduras congelada', id: 588 },
  { label: 'Menestra de verduras', id: 589 },
  { label: 'Menta fresca', id: 590 },
  { label: 'Merengue', id: 591 },
  { label: 'Merluza', id: 592 },
  { label: 'Merluza rebozada frita', id: 593 },
  { label: 'Merluza cruda', id: 594 },
  { label: 'Merluza congelada cruda', id: 595 },
  { label: 'Mermelada de Melocotón', id: 596 },
  { label: 'Mermelada de albaricoque y Melocotón', id: 597 },
  { label: 'Mermelada de ciruela', id: 598 },
  { label: 'Mermelada de fresa', id: 599 },
  { label: 'Mermelada de grosella roja', id: 600 },
  { label: 'Mermelada de mora', id: 601 },
  { label: 'Mermelada de naranja', id: 602 },
  { label: 'Mero plancha', id: 603 },
  { label: 'Mero', id: 604 },
  { label: 'Mero crudo', id: 605 },
  { label: 'Mezcla de frutos secos y pasas', id: 606 },
  { label: 'Miel', id: 607 },
  { label: 'Mijo', id: 608 },
  { label: 'Mijo cocido', id: 609 },
  { label: 'Milhojas con nata y crema', id: 610 },
  { label: 'Miso salsa', id: 611 },
  { label: 'Mojo picón salsa', id: 612 },
  { label: 'Molleja de cordero cruda', id: 613 },
  { label: 'Molleja de cordero asada', id: 614 },
  { label: 'Molleja de ternera asada', id: 615 },
  { label: 'Molleja de ternera cruda', id: 616 },
  { label: 'Mora cruda', id: 617 },
  { label: 'Morcilla cruda', id: 618 },
  { label: 'Morcilla cocida', id: 619 },
  { label: 'Mortadela', id: 620 },
  { label: 'Mostaza', id: 621 },
  { label: 'Mousse de chocolate ', id: 622 },
  { label: 'Mousse de queso fresco con frutas', id: 623 },
  { label: 'Mousse de queso fresco desnatado con frutas', id: 624 },
  { label: 'Mousse de yogur con frutas', id: 625 },
  { label: 'Mousse de yogur natural', id: 626 },
  { label: 'Muesli', id: 627 },
  { label: 'Muesli natural sin Azúcar', id: 628 },
  { label: 'Mujol', id: 629 },
  { label: 'Mujol crudo', id: 630 },
  { label: 'Muslito de mar', id: 631 },
  { label: 'Nabo pelado crudo', id: 632 },
  { label: 'Nabo hervido', id: 633 },
  { label: 'Napolitana rellena con crema de cacao', id: 634 },
  { label: 'Naranja', id: 635 },
  { label: 'Nata lí\xadquida para montar (35% grasa)', id: 636 },
  { label: 'Nata para cocinar (18% de grasa)', id: 637 },
  { label: 'Natilla de chocolate', id: 638 },
  { label: 'Natilla de vainilla', id: 639 },
  { label: 'Nécora cruda', id: 640 },
  { label: 'Nécora cocida', id: 641 },
  { label: 'Nécora', id: 642 },
  { label: 'Nécora congelada', id: 643 },
  { label: 'Néctar de albaricoque envasado', id: 644 },
  { label: 'Néctar de ciruela', id: 645 },
  { label: 'Néctar de frutas exóticas envasado', id: 646 },
  { label: 'Néctar de mango envasado', id: 647 },
  { label: 'Néctar de maracuyá envasado', id: 648 },
  { label: 'Néctar de Melocotón', id: 649 },
  { label: 'Néctar de naranja envasado', id: 650 },
  { label: 'Néctar de pera envasado', id: 651 },
  { label: 'Néctar de Piña', id: 652 },
  { label: 'Néctar de pomelo', id: 653 },
  { label: 'Nectarina', id: 654 },
  { label: 'Ní\xadscalo crudo', id: 655 },
  { label: 'Ní\xadscalo', id: 656 },
  { label: 'Ní\xadspero con piel crudo', id: 657 },
  { label: 'Nuez pelada cruda natural', id: 658 },
  { label: 'Nuez de macadamia natural', id: 659 },
  { label: 'Nuez pecana natural', id: 660 },
  { label: 'Nuez moscada', id: 661 },
  { label: 'Nuggets de pollo', id: 662 },
  { label: 'Oca con piel asada', id: 663 },
  { label: 'Orégano seco', id: 664 },
  { label: 'Ostra cruda', id: 665 },
  { label: 'Ostra', id: 666 },
  { label: 'Paella', id: 667 },
  { label: 'Paella marinera', id: 668 },
  { label: 'Palmeritas de hojaldre', id: 669 },
  { label: 'Palmito', id: 670 },
  { label: 'Palometa cruda', id: 671 },
  { label: 'Palometa', id: 672 },
  { label: 'Palomitas de maíz con aceite sin sal', id: 673 },
  { label: 'Palomitas de maíz con aceite con sal', id: 674 },
  { label: 'Pan blanco de barra ', id: 675 },
  { label: 'Pan blanco de barra sin sal', id: 676 },
  { label: 'Pan blanco tipo baguette', id: 677 },
  { label: 'Pan de centeno', id: 678 },
  { label: 'Pan de centeno y trigo', id: 679 },
  { label: 'Pan de avena', id: 680 },
  { label: 'Pan de cebada', id: 681 },
  { label: 'Pan integral de barra', id: 682 },
  { label: 'Pan integral de barra sin sal', id: 683 },
  { label: 'Pan de maíz', id: 684 },
  { label: 'Pan de molde blanco', id: 685 },
  { label: 'Pan de molde integral', id: 686 },
  { label: 'Pan de pasas', id: 687 },
  { label: 'Pan hamburgesa', id: 688 },
  { label: 'Pan Hotdog', id: 689 },
  { label: 'Pan rallado', id: 690 },
  { label: 'Pan rústico (tipo payés)', id: 691 },
  { label: 'Pan sin gluten', id: 692 },
  { label: 'Panela', id: 693 },
  { label: 'Pannini de jamón y queso', id: 694 },
  { label: 'Panceta frita', id: 695 },
  { label: 'Panceta de cerdo ahumada cruda', id: 696 },
  { label: 'Panga cruda', id: 697 },
  { label: 'Panga congelada', id: 698 },
  { label: 'Panga', id: 699 },
  { label: 'Papaya cruda', id: 700 },
  { label: 'Paraguaya cruda', id: 701 },
  { label: 'Pasta alimenticia con huevo cruda', id: 702 },
  { label: 'Pasta alimenticia con huevo hervida', id: 703 },
  { label: 'Pasta alimenticia con vegetales cruda', id: 704 },
  { label: 'Pasta alimenticia cruda', id: 705 },
  { label: 'Pasta alimenticia hervida', id: 706 },
  { label: 'Pasta alimenticia integral cruda', id: 707 },
  { label: 'Pasta alimenticia integral hervida', id: 708 },
  { label: 'Pasta alimenticia rellena con carne hervida', id: 709 },
  { label: 'Pasta alimenticia rellena de queso hervida', id: 710 },
  { label: 'Pasta alimenticia lentejas rojas', id: 711 },
  { label: 'Pasta sin gluten', id: 712 },
  { label: 'Pasta con gluten hervida', id: 713 },
  { label: 'Pastas pequeñas de té', id: 714 },
  { label: 'Pastel con fruta confitada', id: 715 },
  { label: 'Pastel de chocolate', id: 716 },
  { label: 'Pastel de manzana', id: 717 },
  { label: 'Pastelito tipo lionesa relleno de crema', id: 718 },
  { label: 'Pastel Saboyana', id: 719 },
  { label: 'Patata', id: 720 },
  { label: 'Patata cruda', id: 721 },
  { label: 'Patata hervida', id: 722 },
  { label: 'Patatas chips ', id: 723 },
  { label: 'Patatas chips lights', id: 724 },
  { label: 'Patatas fritas con aceite s/e con sal', id: 725 },
  { label: 'Paté de campaña', id: 726 },
  { label: 'Paté de pimienta', id: 727 },
  { label: 'Paté de hí\xadgado de cerdo', id: 728 },
  { label: 'Pato entero asado', id: 729 },
  { label: 'Pato entero con piel crudo', id: 730 },
  { label: 'Pavo fiambre', id: 731 },
  { label: 'Pavo muslo con piel crudo', id: 732 },
  { label: 'Pavo pechuga con piel', id: 733 },
  { label: 'Pavo pechuga con piel cruda', id: 734 },
  { label: 'Pavo pechuga con piel cocida', id: 735 },
  { label: 'Pavo con piel asado', id: 736 },
  { label: 'Pavo con piel crudo', id: 737 },
  { label: 'Pepinillos', id: 738 },
  { label: 'Pepino', id: 739 },
  { label: 'Pera enlatada', id: 740 },
  { label: 'Pera con piel cruda', id: 741 },
  { label: 'Pera sin piel cruda', id: 742 },
  { label: 'Perca', id: 743 },
  { label: 'Perca cruda', id: 744 },
  { label: 'Perca congelada', id: 745 },
  { label: 'Percebe crudo', id: 746 },
  { label: 'Percebe cocido', id: 747 },
  { label: 'Perdiz cruda', id: 748 },
  { label: 'Perdiz', id: 749 },
  { label: 'Perdiz asada', id: 750 },
  { label: 'Perdiz estofada', id: 751 },
  { label: 'Perejil fresco', id: 752 },
  { label: 'Pescadilla', id: 753 },
  { label: 'Pescadilla cruda', id: 754 },
  { label: 'Pescadilla congelada', id: 755 },
  { label: 'Pescadilla rebozada', id: 756 },
  { label: 'Petit suísse cereales y fruta', id: 757 },
  { label: 'Petit suisse fresa', id: 758 },
  { label: 'Petit suisse líquido sabor fresa', id: 759 },
  { label: 'Petit Suisse natural azucarado', id: 760 },
  { label: 'Petit-suisse con frutas', id: 761 },
  { label: 'Petit-suisse chocolate', id: 762 },
  { label: 'Pez espada', id: 763 },
  { label: 'Pez espada crudo', id: 764 },
  { label: 'Pez espada cocido', id: 765 },
  { label: 'Picatostes tostados', id: 766 },
  { label: 'Pichón con piel asado', id: 767 },
  { label: 'Pimentón dulce', id: 768 },
  { label: 'Pimienta blanca', id: 769 },
  { label: 'Pimienta negra', id: 770 },
  { label: 'Pimiento rojo hervido', id: 771 },
  { label: 'Pimiento rojo', id: 772 },
  { label: 'Pimiento verde hervido', id: 773 },
  { label: 'Pimiento verde', id: 774 },
  { label: 'Pimiento rojo crudo', id: 775 },
  { label: 'Pimiento verde crudo', id: 776 },
  { label: 'Pimiento morrón', id: 777 },
  { label: 'Piña', id: 778 },
  { label: 'Piña cruda', id: 779 },
  { label: 'Piña enlatada', id: 780 },
  { label: 'Piñones', id: 781 },
  { label: 'Piñones tostados', id: 782 },
  { label: 'Pipas de calabaza', id: 783 },
  { label: 'Pipas de girasol con sal', id: 784 },
  { label: 'Pipas de girasol sin sal', id: 785 },
  { label: 'Pistacho crudo sin sal', id: 786 },
  { label: 'Pistacho tostado salado', id: 787 },
  { label: 'Pistacho tostado sin sal', id: 788 },
  { label: 'Pizza 4 quesos', id: 789 },
  { label: 'Pizza boloñesa', id: 790 },
  { label: 'Pizza caprichosa', id: 791 },
  { label: 'Pizza de Jamón y queso', id: 792 },
  { label: 'Plátano', id: 793 },
  { label: 'Platija', id: 794 },
  { label: 'Platija cruda', id: 795 },
  { label: 'Platija congelada', id: 796 },
  { label: 'Pollo ala con piel cruda', id: 797 },
  { label: 'Pollo fiambre', id: 798 },
  { label: 'Pollo con piel crudo', id: 799 },
  { label: 'Pollo entero con piel asado', id: 800 },
  { label: 'Pollo empanado frito', id: 801 },
  { label: 'Pollo muslo con piel asado', id: 802 },
  { label: 'Pollo muslo con piel crudo', id: 803 },
  { label: 'Pollo pechuga con piel crudo', id: 804 },
  { label: 'Pollo pechuga con piel plancha', id: 805 },
  { label: 'Pomelo', id: 806 },
  { label: 'Polo sabor s/e', id: 807 },
  { label: 'Potito de arroz blanco y pollo', id: 808 },
  { label: 'Potito de arroz y merluza', id: 809 },
  { label: 'Potito de cordero y verdura', id: 810 },
  { label: 'Potito de frutas', id: 811 },
  { label: 'Potito de guisantes con jamon', id: 812 },
  { label: 'Potito de jardinera de la huerta', id: 813 },
  { label: 'Potito de lenguado con bechamel', id: 814 },
  { label: 'Potito de verdura con pollo', id: 815 },
  { label: 'Potito de verduras con ternera', id: 816 },
  { label: 'Potito de verduras y lubina', id: 817 },
  { label: 'Potito de verduras y pavo', id: 818 },
  { label: 'Potito de verduras pollo y ternera', id: 819 },
  { label: 'Potito frutas con galleta', id: 820 },
  { label: 'Potito verdura y pescadilla', id: 821 },
  { label: 'Psyllium', id: 822 },
  { label: 'Pudding de pasas', id: 823 },
  { label: 'Puerro crudo', id: 824 },
  { label: 'Puerro', id: 825 },
  { label: 'Puerro hervido', id: 826 },
  { label: 'Pulmón de ternera crudo', id: 827 },
  { label: 'Pulmón de cordero crudo', id: 828 },
  { label: 'Pulmón de cerdo crudo', id: 829 },
  { label: 'Pulpo crudo', id: 830 },
  { label: 'Pulpo', id: 831 },
  { label: 'Pulpo cocido', id: 832 },
  { label: 'Puré de patata y queso', id: 833 },
  { label: 'Puré de patata con verduras', id: 834 },
  { label: 'Puré de patata', id: 835 },
  { label: 'Puré de patata con leche', id: 836 },
  { label: 'Quesito', id: 837 },
  { label: 'Queso Camembert 20-30% MG/ES', id: 838 },
  { label: 'Queso Camembert 60% MG/ES', id: 839 },
  { label: 'Queso Castellano', id: 840 },
  { label: 'Queso Cheddar', id: 841 },
  { label: 'Queso crema', id: 842 },
  { label: 'Queso crema light', id: 843 },
  { label: 'Queso curado genérico', id: 844 },
  { label: 'Queso de Arzúa', id: 845 },
  { label: 'Queso azul', id: 846 },
  { label: 'Queso Brie', id: 847 },
  { label: 'Queso de cabra curado', id: 848 },
  { label: 'Queso de cabra semicurado', id: 849 },
  { label: 'Queso cabrales', id: 850 },
  { label: 'Queso de Castilla-La Mancha oveja y cabra', id: 851 },
  { label: 'Queso de Castilla-La Mancha oveja vaca y cabra', id: 852 },
  { label: 'Queso de Castilla-León oveja y vaca', id: 853 },
  { label: 'Queso edam', id: 854 },
  { label: 'Queso emmental', id: 855 },
  { label: 'Queso', id: 856 },
  { label: 'Queso fresco (tipo Burgos)', id: 857 },
  { label: 'Queso fresco cabra', id: 858 },
  { label: 'Queso fundido extragraso (>60% MG/ES)', id: 859 },
  { label: 'Queso Gouda', id: 860 },
  { label: 'Queso Gruyere', id: 861 },
  { label: 'Queso Ibores', id: 862 },
  { label: 'Queso Mahón', id: 863 },
  { label: 'Queso majorero', id: 864 },
  { label: 'Queso manchego curación s/e', id: 865 },
  { label: 'Queso Manchego', id: 866 },
  { label: 'Queso mozzarella', id: 867 },
  { label: 'Queso Munster', id: 868 },
  { label: 'Queso para untar con finas hierbas', id: 869 },
  { label: 'Queso parmesano', id: 870 },
  { label: 'Queso Raclette', id: 871 },
  { label: 'Queso ricotta', id: 872 },
  { label: 'Queso Roquefort', id: 873 },
  { label: 'Queso San Simón', id: 874 },
  { label: 'Queso semicurado', id: 875 },
  { label: 'Queso Tetilla', id: 876 },
  { label: 'Queso tierno', id: 877 },
  { label: 'Queso torta del casar', id: 878 },
  { label: 'Queso Zamorano', id: 879 },
  { label: 'Quinoa cruda', id: 880 },
  { label: 'Quinoa cocida', id: 881 },
  { label: 'Rábano crudo', id: 882 },
  { label: 'Rábano cocido', id: 883 },
  { label: 'Rábano', id: 884 },
  { label: 'Rabo de toro', id: 885 },
  { label: 'Rabo de toro cocido', id: 886 },
  { label: 'Rana anca cruda', id: 887 },
  { label: 'Rana anca', id: 888 },
  { label: 'Rana anca cocida', id: 889 },
  { label: 'Rape', id: 890 },
  { label: 'Rape crudo', id: 891 },
  { label: 'Raya cruda', id: 892 },
  { label: 'Raya', id: 893 },
  { label: 'Raya congelada', id: 894 },
  { label: 'Raya guisada', id: 895 },
  { label: 'Refresco aroma lima-Limón con gas', id: 896 },
  { label: 'Refresco de té', id: 897 },
  { label: 'Refresco sabor cola con gas', id: 898 },
  { label: 'Refresco sabor cola light con gas', id: 899 },
  { label: 'Refresco sabor cola con cafeí\xadna', id: 900 },
  { label: 'Refresco sabor cola light con cafeí\xadna', id: 901 },
  { label: 'Refresco sabor Limón con gas', id: 902 },
  { label: 'Refresco sabor naranja con gas', id: 903 },
  { label: 'Refresco tipo gaseosa', id: 904 },
  { label: 'Refresco tónica con gas', id: 905 },
  { label: 'Regaliz', id: 906 },
  { label: 'Remolacha cruda', id: 907 },
  { label: 'Remolacha cocida y pelada', id: 908 },
  { label: 'Remolacha', id: 909 },
  { label: 'Repollo', id: 910 },
  { label: 'Repollo hervido', id: 911 },
  { label: 'Requesón', id: 912 },
  { label: 'Riñón de cerdo crudo', id: 913 },
  { label: 'Riñón de cordero crudo', id: 914 },
  { label: 'Riñón de ternera crudo', id: 915 },
  { label: 'Rodaballo crudo', id: 916 },
  { label: 'Rodaballo cocido', id: 917 },
  { label: 'Rodaballo', id: 918 },
  { label: 'Rollito de primavera', id: 919 },
  { label: 'Romero fresco', id: 920 },
  { label: 'Ron', id: 921 },
  { label: 'Rosquilletas', id: 922 },
  { label: 'Rosquilletas con pipas', id: 923 },
  { label: 'Rúcula', id: 924 },
  { label: 'Sal de mar', id: 925 },
  { label: 'Sal común', id: 926 },
  { label: 'Sal rosa', id: 927 },
  { label: 'Sal yodada', id: 928 },
  { label: 'Salami', id: 929 },
  { label: 'Salchicha fresca cruda', id: 930 },
  { label: 'Salchicha tipo paí\xads', id: 931 },
  { label: 'Salchicha tipo viena', id: 932 },
  { label: 'Salchicha tipo frankfurt cruda', id: 933 },
  { label: 'Salchichón', id: 934 },
  { label: 'Salema cruda', id: 935 },
  { label: 'Salema', id: 936 },
  { label: 'Salema plancha', id: 937 },
  { label: 'Salmón ahumado', id: 938 },
  { label: 'Salmón', id: 939 },
  { label: 'Salmón crudo', id: 940 },
  { label: 'Salmonete crudo', id: 941 },
  { label: 'Salmonete', id: 942 },
  { label: 'Salmonete cocido', id: 943 },
  { label: 'Salsa', id: 944 },
  { label: 'Salsa agridulce', id: 945 },
  { label: 'Salsa barbacoa', id: 946 },
  { label: 'Salsa bechamel', id: 947 },
  { label: 'Salsa beamesa', id: 948 },
  { label: 'Salsa boloñesa', id: 949 },
  { label: 'Salsa carbonara', id: 950 },
  { label: 'Salsa césar', id: 951 },
  { label: 'Salsa de soja', id: 952 },
  { label: 'Salsa de queso', id: 953 },
  { label: 'Salsa de tomate comercial envasada', id: 954 },
  { label: 'Salsa holandesa', id: 955 },
  { label: 'Salsa napolitana', id: 956 },
  { label: 'Salsa momay', id: 957 },
  { label: 'Salsa pesto', id: 958 },
  { label: 'Salsa siciliana picante', id: 959 },
  { label: 'Salsa vinagreta con aceite de oliva', id: 960 },
  { label: 'Salsafi', id: 961 },
  { label: 'Salvado de avena', id: 962 },
  { label: 'Salvado de trigo ', id: 963 },
  { label: 'Sandwich caliente de Jamón y queso', id: 964 },
  { label: 'Sandí\xada', id: 965 },
  { label: 'Sangrí\xada de vino tinto', id: 966 },
  { label: 'Sardina cruda ', id: 967 },
  { label: 'Sardina ahumada', id: 968 },
  { label: 'Sardina', id: 969 },
  { label: 'Sardina cocida', id: 970 },
  { label: 'Sardina enlatada', id: 971 },
  { label: 'Sargo crudo', id: 972 },
  { label: 'Sargo', id: 973 },
  { label: 'Sargo cocido', id: 974 },
  { label: 'Seitán crudo', id: 975 },
  { label: 'Seitán', id: 976 },
  { label: 'Semillas de amaranto', id: 977 },
  { label: 'Semillas de chía', id: 978 },
  { label: 'Semillas de lino', id: 979 },
  { label: 'Sémola de arroz', id: 980 },
  { label: 'Sémola de trigo cruda', id: 981 },
  { label: 'Sémola de trigo hervida', id: 982 },
  { label: 'Sepia cruda', id: 983 },
  { label: 'Sepia', id: 984 },
  { label: 'Sepia cocida', id: 985 },
  { label: 'Sepia congelada', id: 986 },
  { label: 'Sésamo semilla', id: 987 },
  { label: 'Sesos de cerdo crudos', id: 988 },
  { label: 'Sesos de cordero crudos', id: 989 },
  { label: 'Sesos de ternera crudos', id: 990 },
  { label: 'Setas', id: 991 },
  { label: 'Setas cocidas', id: 992 },
  { label: 'Sidra dulce', id: 993 },
  { label: 'Sidra seca', id: 994 },
  { label: 'Sirope de agave', id: 995 },
  { label: 'Sobao', id: 996 },
  { label: 'Sobrasada', id: 997 },
  { label: 'Soda', id: 998 },
  { label: 'Soja frita', id: 999 },
  { label: 'Soja texturizada', id: 1000 },
  { label: 'Soja fresca', id: 1001 },
  { label: 'Soja germinada', id: 1002 },
  { label: 'Soja harina', id: 1003 },
  { label: 'Soja seca cruda', id: 1004 },
  { label: 'Soja seca remojada hervida', id: 1005 },
  { label: 'Solomillo de vaca/buey', id: 1006 },
  { label: 'Solomillo de vaca/buey crudo', id: 1007 },
  { label: 'Solomillo de cerdo', id: 1008 },
  { label: 'Solomillo de cerdo crudo', id: 1009 },
  { label: 'Solomillo de ternera con grasa crudo', id: 1010 },
  { label: 'Solomillo de ternera', id: 1011 },
  { label: 'Sorbete sabor s/e', id: 1012 },
  { label: 'Stevia', id: 1013 },
  { label: 'Sucedáneo del Café', id: 1014 },
  { label: 'Surimi', id: 1015 },
  { label: 'Tabasco salsa', id: 1016 },
  { label: 'Tahini salsa', id: 1017 },
  { label: 'Tapioca cruda', id: 1018 },
  { label: 'Tapioca hervida', id: 1019 },
  { label: 'Té Infusión ', id: 1020 },
  { label: 'Té Infusión con leche', id: 1021 },
  { label: 'Tempeh', id: 1022 },
  { label: 'Tempeh cocido', id: 1023 },
  { label: 'Tenca cruda', id: 1024 },
  { label: 'Tenca', id: 1025 },
  { label: 'Tenca cocida', id: 1026 },
  { label: 'Tenca congelada', id: 1027 },
  { label: 'Tequila', id: 1028 },
  { label: 'Ternera paletilla cruda', id: 1029 },
  { label: 'Ternera paletilla cocida', id: 1030 },
  { label: 'Ternera paletilla', id: 1031 },
  { label: 'Ternera entrecot con grasa crudo', id: 1032 },
  { label: 'Ternera entrecot con grasa', id: 1033 },
  { label: 'Ternera entrecot cocido', id: 1034 },
  { label: 'Ternera costillar crudo', id: 1035 },
  { label: 'Ternera costillar cocido', id: 1036 },
  { label: 'Ternera costillar', id: 1037 },
  { label: 'Ternera redondo filete cocido', id: 1038 },
  { label: 'Ternera costilla cruda', id: 1039 },
  { label: 'Ternera lomo crudo con grasa separable', id: 1040 },
  { label: 'Ternera lomo', id: 1041 },
  { label: 'Ternera lomo cocido', id: 1042 },
  { label: 'Ternera parte s/e asada', id: 1043 },
  { label: 'Tocino', id: 1044 },
  { label: 'Tocino cocido', id: 1045 },
  { label: 'Tofu', id: 1046 },
  { label: 'Tofu cocido', id: 1047 },
  { label: 'Tomate asado', id: 1048 },
  { label: 'Tomate maduro crudo', id: 1049 },
  { label: 'Tomate cocido', id: 1050 },
  { label: 'Tomate frito', id: 1051 },
  { label: 'Tomate pelado enlatado', id: 1052 },
  { label: 'Tomate pelado y triturado enlatado', id: 1053 },
  { label: 'Tomillo', id: 1054 },
  { label: 'Toronja', id: 1055 },
  { label: 'Tortelini 4 quesos', id: 1056 },
  { label: 'Tortelini de carne', id: 1057 },
  { label: 'Tortilla', id: 1058 },
  { label: 'Tortilla de patata', id: 1059 },
  { label: 'Tortitas de maíz', id: 1060 },
  { label: 'Trigo hinchado', id: 1061 },
  { label: 'Trigo sarraceno', id: 1062 },
  { label: 'Trigo candeal o tierno', id: 1063 },
  { label: 'Trigo entero crudo', id: 1064 },
  { label: 'Trucha', id: 1065 },
  { label: 'Trucha cruda', id: 1066 },
  { label: 'Trucha congelada', id: 1067 },
  { label: 'Trucha ahumada', id: 1068 },
  { label: 'Trufa cruda', id: 1069 },
  { label: 'Turrón tipo Alicante', id: 1070 },
  { label: 'Turrón tipo Jijona', id: 1071 },
  { label: 'Uva pasa', id: 1072 },
  { label: 'Uva blanca', id: 1073 },
  { label: 'Uva blanca congelada', id: 1074 },
  { label: 'Uva negra cruda', id: 1075 },
  { label: 'Vaca/buey entrecot con grasa', id: 1076 },
  { label: 'Vaca/buey entrecot', id: 1077 },
  { label: 'Vaca/buey parte s/e asado', id: 1078 },
  { label: 'Vaca/buey parte s/e bistec', id: 1079 },
  { label: 'Vaca/buey parte s/e estofado', id: 1080 },
  { label: 'Vaca/Buey redondo asado', id: 1081 },
  { label: 'Vaca/buey falda cruda', id: 1082 },
  { label: 'Vaca/buey falda cocida', id: 1083 },
  { label: 'Vainilla lí\xadquida', id: 1084 },
  { label: 'Varitas de merluza', id: 1085 },
  { label: 'Vermut s/e', id: 1086 },
  { label: 'Vermut negro dulce', id: 1087 },
  { label: 'Vieira cruda', id: 1088 },
  { label: 'Vieira', id: 1089 },
  { label: 'Vieira cocida', id: 1090 },
  { label: 'Vieja cruda', id: 1091 },
  { label: 'Vieja congelada', id: 1092 },
  { label: 'Vieja', id: 1093 },
  { label: 'Vinagre balsámico', id: 1094 },
  { label: 'Vinagre de manzana', id: 1095 },
  { label: 'Vinagre de vino', id: 1096 },
  { label: 'Vino blanco', id: 1097 },
  { label: 'Vino dulce tipo Moscatel', id: 1098 },
  { label: 'Vino tinto', id: 1099 },
  { label: 'Vodka', id: 1100 },
  { label: 'Volador crudo', id: 1101 },
  { label: 'Volador cocido', id: 1102 },
  { label: 'Volador', id: 1103 },
  { label: 'Whisky', id: 1104 },
  { label: 'Xilitol', id: 1105 },
  { label: 'Yogur de queso fresco batido', id: 1106 },
  { label: 'Yogur de soja', id: 1107 },
  { label: 'Yogur líquido entero sabor Piña y coco', id: 1108 },
  { label: 'Yogur líquido entero sabor fresa plátano', id: 1109 },
  { label: 'Yogur líquido aromatizado sabor s/e', id: 1110 },
  { label: 'Yogur líquido natural azucarado', id: 1111 },
  { label: 'Yogur líquido con frutas s/e', id: 1112 },
  { label: 'Yogur líquido desnatado natural', id: 1113 },
  { label: 'Yogur líquido entero con cereales y fresas', id: 1114 },
  { label: 'Yogur desnatado natural', id: 1115 },
  { label: 'Yogur desnatado natural edulcorado', id: 1116 },
  { label: 'Yogur entero natural ', id: 1117 },
  { label: 'Yogur entero aromatizado sabor s/e', id: 1118 },
  { label: 'Yogur entero con frutas s/e', id: 1119 },
  { label: 'Yogur entero con fresas', id: 1120 },
  { label: 'Yogur skyr', id: 1121 },
  { label: 'Yogur tipo griego', id: 1122 },
  { label: 'Yogur desnatado aromatizado sabor s/e', id: 1123 },
  { label: 'Yogur desnatado con cereales', id: 1124 },
  { label: 'Yogur desnatado con cereza y frambuesa', id: 1125 },
  { label: 'Yogur desnatado con frutas', id: 1126 },
  { label: 'Yogur desnatado con frutas del bosque', id: 1127 },
  { label: 'Yogur desnatado con frutas tropicales', id: 1128 },
  { label: 'Yogur desnatado con manzana', id: 1129 },
  { label: 'Yogur desnatado con Melocotón y maracuyá', id: 1130 },
  { label: 'Yogur desnatado con Piña y pomelo', id: 1131 },
  { label: 'Yogur desnatado sabor vainilla', id: 1132 },
  { label: 'Yogur enriquecido con frutas', id: 1133 },
  { label: 'Yogur enriquecido natural', id: 1134 },
  { label: 'Yogur enriquecido natural azucarado', id: 1135 },
  { label: 'Yogur enriquecido natural con nata', id: 1136 },
  { label: 'Yogur enriquecido sabor s/e', id: 1137 },
  { label: 'Zamburiñas crudas', id: 1138 },
  { label: 'Zamburiñas cocidas', id: 1139 },
  { label: 'Zamburiñas', id: 1140 },
  { label: 'Zanahoria hervida', id: 1141 },
  { label: 'Zanahoria', id: 1142 },
  { label: 'Zanahoria cruda', id: 1143 },
  { label: 'Zanahoria baby ultracongelada', id: 1144 },
  { label: 'Zumo bifrutas fresa y plátano', id: 1145 },
  { label: 'Zumo bifrutas Ibiza', id: 1146 },
  { label: 'Zumo bifrutas Tropical', id: 1147 },
  { label: 'Zumo con leche', id: 1148 },
  { label: 'Zumo de grosella negra', id: 1149 },
  { label: 'Zumo de grosella roja', id: 1150 },
  { label: 'Zumo de lima envasado', id: 1151 },
  { label: 'Zumo de mango', id: 1152 },
  { label: 'Zumo de manzana', id: 1153 },
  { label: 'Zumo de Melocotón', id: 1154 },
  { label: 'Zumo de naranja', id: 1155 },
  { label: 'Zumo de Piña', id: 1156 },
  { label: 'Zumo de Piña y uva', id: 1157 },
  { label: 'Zumo de pomelo envasado', id: 1158 },
  { label: 'Zumo de uva y Melocotón', id: 1159 },
  { label: 'Zumo Minute Maid duofrutas', id: 1160 },
  { label: 'Zumo Yosport', id: 1161 },
  { label: 'Zumo de frutas exóticas', id: 1162 },
  { label: 'Zumo de pera envasado', id: 1163 },
  { label: 'Zumo de tomate envasado', id: 1164 },
  { label: 'Zumo de uva envasado', id: 1165 },
  { label: 'Zumo de zanahoria envasado', id: 1166 },
  { label: 'Zumo de Limón', id: 1167 },
  { label: 'Batata cruda', id: 1168 },
  { label: 'Batata', id: 1169 },
  { label: 'Batata hervida', id: 1170 },
  { label: 'Ajo negro natural', id: 1171 },
  { label: 'Chalota cruda', id: 1172 },
  { label: 'Chalota hervida', id: 1173 },
  { label: 'Chalota', id: 1174 },
  { label: 'Cebolla tierna cruda', id: 1175 },
  { label: 'Cebolla tierna hervida', id: 1176 },
  { label: 'Cebolla tierna', id: 1177 },
  { label: 'Bimi crudo', id: 1178 },
  { label: 'Bimi hervido', id: 1179 },
  { label: 'Bimi', id: 1180 },
  { label: 'Nabicol crudo', id: 1181 },
  { label: 'Nabicol hervido', id: 1182 },
  { label: 'Nabicol', id: 1183 },
  { label: 'Judí\xada verde plana cruda', id: 1184 },
  { label: 'Judí\xada verde plana hervida', id: 1185 },
  { label: 'Judí\xada verde plana', id: 1186 },
  { label: 'Judí\xada verde plana congelada cruda', id: 1187 },
  { label: 'Tomate cherry', id: 1188 },
  { label: 'Tomate seco', id: 1189 },
  { label: 'Pimientos del piquillo', id: 1190 },
  { label: 'Pimiento rojo asado', id: 1191 },
  { label: 'Pimientos choriceros', id: 1192 },
  { label: 'Pimientos semipicantes', id: 1193 },
  { label: 'Yuca cruda', id: 1194 },
  { label: 'Yuca hervida', id: 1195 },
  { label: 'Yuca', id: 1196 },
  { label: 'Alubia pinta', id: 1197 },
  { label: 'Albahaca', id: 1198 },
  { label: 'Aní\xads', id: 1199 },
  { label: 'Clavo', id: 1200 },
  { label: 'Cebollino', id: 1201 },
  { label: 'Cilantro', id: 1202 },
  { label: 'Cúrcuma', id: 1203 },
  { label: 'Cebolla', id: 1204 },
  { label: 'Hierbas provenzales', id: 1205 },
  { label: 'Hierbabuena', id: 1206 },
  { label: 'Pebrella', id: 1207 },
  { label: 'Pimentón picante', id: 1208 },
  { label: 'Jengibre molido', id: 1209 },
  { label: 'Ñoras', id: 1210 },
  { label: 'Aceite de aguacate', id: 1211 },
  { label: 'Vinagre balsámico de manzana', id: 1212 },
  { label: 'Vinagre reducción Pedro Ximénez', id: 1213 },
  { label: 'Fideos de trigo blancos', id: 1214 },
  { label: 'Fideos de trigo integrales', id: 1215 },
  { label: 'Fideos', id: 1216 },
  { label: 'Fideos con gluten', id: 1217 },
  { label: 'Fideuá', id: 1218 },
  { label: 'Espaguetti de trigo', id: 1219 },
  { label: 'Espaguetti de trigo integral', id: 1220 },
  { label: 'Esapaguetti', id: 1221 },
  { label: 'Espaguetti con gluten', id: 1222 },
  { label: 'Nidos', id: 1223 },
  { label: 'Nidos con vegetales', id: 1224 },
  { label: 'Macarrones', id: 1225 },
  { label: 'Macarrones integrales', id: 1226 },
  { label: 'Macarrones con gluten', id: 1227 },
  { label: 'Hélices con vegetales', id: 1228 },
  { label: 'Pajaritas con vegetales', id: 1229 },
  { label: 'Placas para lasaña ', id: 1230 },
  { label: 'Placas para lasaña con gluten', id: 1231 },
  { label: 'Placas para canelones', id: 1232 },
  { label: 'Placas para canelones sin gluten', id: 1233 },
  { label: 'Gnocchi', id: 1234 },
  { label: 'Mojama', id: 1235 },
  { label: 'Camarón', id: 1236 },
  { label: 'Cigala cruda', id: 1237 },
  { label: 'Cigala', id: 1238 },
  { label: 'Cigala cruda congelada', id: 1239 },
  { label: 'Navajas crudas', id: 1240 },
  { label: 'Navajas', id: 1241 },
  { label: 'Navajas crudas congeladas', id: 1242 },
  { label: 'Huevas', id: 1243 },
  { label: 'Cerdo osobuco', id: 1244 },
  { label: 'Cerdo a tacos', id: 1245 },
  { label: 'Cerdo patas', id: 1246 },
  { label: 'Cerdo codillo', id: 1247 },
  { label: 'Cerdo secreto', id: 1248 },
  { label: 'Cerdo chuleta lomo con grasa cruda', id: 1249 },
  { label: 'Cerdo rabo', id: 1250 },
  { label: 'Pollo jamoncitos', id: 1251 },
  { label: 'Pavo chuletas', id: 1252 },
  { label: 'Pavo solomillo', id: 1253 },
  { label: 'Pavo', id: 1254 },
  { label: 'Vacuno churrasco', id: 1255 },
  { label: 'Vacuno carpaccio', id: 1256 },
  { label: 'Cordero costilla con grasa cruda', id: 1257 },
  { label: 'Ajo tierno', id: 1258 },
  { label: 'Spirulina', id: 1259 },
  { label: 'Cereales desayuno espelta sin azúcar', id: 1260 },
  { label: 'Pasta alimenticia de arroz', id: 1261 },
  { label: 'Pasta alimenticia de trigo sarraceno', id: 1262 },
  { label: 'Yogur vegetal de coco y soja', id: 1263 },
  { label: 'Yogur vegetal skyr', id: 1264 },
  { label: 'Pimiento amarillo crudo', id: 1265 },
  { label: 'Kale crudo', id: 1266 },
  { label: 'Harina de garbanzo', id: 1267 },
  { label: 'Tortita integral de trigo fajitas', id: 1268 },
  { label: 'Tortita de trigo fajitas', id: 1269 },
  { label: 'Seta cruda', id: 1270 },
  { label: 'Pan multicereal', id: 1271 },
  { label: 'Pan cinco semillas y fibra', id: 1272 },
  { label: 'Pan integral de espelta', id: 1273 },
  { label: 'Yogur de soja light', id: 1274 },
  { label: 'Proteína de suero', id: 1275 },
  { label: 'Proteína de guisante', id: 1276 },
  { label: 'Proteína de soja', id: 1277 },
  { label: 'Levadura', id: 1278 },
];

export const categories = {
  1: 'Cereales y derivados',
  2: 'Huevos y lácteos',
  3: 'Carne y derivados',
  4: 'Frutas',
  5: 'Verduras y hortalizas',
  6: 'Grasas y aceites',
  9: 'Pescados y mariscos',
  10: 'Otros',
  12: 'Legumbres y derivados',
  14: 'Especias y salsas',
};
